/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OpcionesMenu;

import BossRush.BossRushTutorial;
import BossRush.BossRushTutorial;
import BossRush.BossRushTutorial;
import BossRush.BossRushTutorial;
import BossRush.Nombre_Boss_Rush;
import BossRush.Nombre_Boss_Rush;
import BossRush.Nombre_Boss_Rush;
import BossRush.Nombre_Boss_Rush;
import BossRush.Nombre_Boss_Rush;
import BossRush.PanelBossRush;
import OpcionesMenu.MenuPrinicipal;
import menucoldware.FrameGeneral;
import InformacionPaneles.InfoBossRush;
import InformacionPaneles.InfoPartidaNormal;
import OpcionesMenu.MenuPrinicipal;
import OpcionesMenu.MenuPrinicipal;
import OpcionesMenu.MenuPrinicipal;
import OpcionesMenu.MenuPrinicipal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author rasca
 */
public class MenuModo extends javax.swing.JPanel implements ActionListener  {

    /**
     * Creates new form EleccionPartida
     */
    public MenuModo() {
        initComponents();
            infoPartidaNormal.addActionListener(this);
            Volver.addActionListener(this);
            infoBossRush.addActionListener(this);
            BossRush.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partidaNornal = new javax.swing.JButton();
        BossRush = new javax.swing.JButton();
        infoBossRush = new javax.swing.JButton();
        infoPartidaNormal = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Tutorial = new javax.swing.JButton();

        partidaNornal.setText("Partida Normal");

        BossRush.setText("Boss Rush");
        BossRush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BossRushActionPerformed(evt);
            }
        });

        infoBossRush.setText("?");

        infoPartidaNormal.setText("?");

        Volver.setText("Volver");

        Tutorial.setText("Tutorial");
        Tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BossRush, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(partidaNornal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(infoPartidaNormal)
                    .addComponent(infoBossRush))
                .addGap(18, 18, 18)
                .addComponent(Tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partidaNornal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoPartidaNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BossRush, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoBossRush, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BossRushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BossRushActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BossRushActionPerformed

    private void TutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorialActionPerformed
        // TODO add your handling code here:
        
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new BossRushTutorial());
	marco.setVisible(true);
        
    }//GEN-LAST:event_TutorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BossRush;
    private javax.swing.JButton Tutorial;
    private javax.swing.JButton Volver;
    private javax.swing.JButton infoBossRush;
    private javax.swing.JButton infoPartidaNormal;
    private javax.swing.JButton partidaNornal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==Volver){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new MenuPrinicipal());
	marco.setVisible(true);
        }
        
            if(e.getSource()==infoPartidaNormal){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new InfoPartidaNormal());
	marco.setVisible(true);
        }
             if(e.getSource()==infoBossRush){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new InfoBossRush());
	marco.setVisible(true);
        }
             
            if(e.getSource()==BossRush){
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new Nombre_Boss_Rush());
	marco.setVisible(true);
        }
             
        
        
        
    }
}
