/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BossRush;

import javax.swing.SwingUtilities;
import menucoldware.FrameGeneral;

/**
 *
 * @author sergipaz
 */
public class Eleccion_Jugador2 extends javax.swing.JPanel {

    /**
     * Creates new form Eleccion_Jugador
     */
    
    int boost_hp;
    int vida_jugador;
    int pamax;
    
    boolean pa;
    boolean fireball;
    
    String Nombre_Usuario;
    
    
    public Eleccion_Jugador2(String Nombre_Usuario,int vida_jugador) {
        initComponents();
        System.out.println(Nombre_Usuario);
        
        this.vida_jugador = vida_jugador;
        Nombre_Jugador.setText(Nombre_Usuario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        curacion_jugador = new javax.swing.JButton();
        pa_max = new javax.swing.JButton();
        fire_ball = new javax.swing.JButton();
        Nombre_Jugador = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 768));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descansi.gif"))); // NOI18N

        curacion_jugador.setText("+50 de HP para ti guapo");
        curacion_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curacion_jugadorActionPerformed(evt);
            }
        });

        pa_max.setText("+ 4 PA maximos");
        pa_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pa_maxActionPerformed(evt);
            }
        });

        fire_ball.setText("+1 Fire Ball");
        fire_ball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fire_ballActionPerformed(evt);
            }
        });

        Nombre_Jugador.setText("Haga su eleccion ");
        Nombre_Jugador.setEnabled(false);

        jLayeredPane2.setLayer(curacion_jugador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(pa_max, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(fire_ball, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Nombre_Jugador, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(curacion_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(pa_max, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(fire_ball, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(608, 608, 608)
                        .addComponent(Nombre_Jugador)))
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Nombre_Jugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curacion_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pa_max, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fire_ball, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(867, 867, 867))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(0, 525, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(0, 261, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void curacion_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curacion_jugadorActionPerformed
        // TODO add your handling code here:
        
        String Nombre_Usuario = Nombre_Jugador.getText();
        
        boost_hp = boost_hp +50;
         
        
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new BossRush3(Nombre_Usuario,boost_hp,pamax,vida_jugador,fireball,pa));
	marco.setVisible(true);
        
    }//GEN-LAST:event_curacion_jugadorActionPerformed

    private void pa_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pa_maxActionPerformed
        // TODO add your handling code here:
        
        String Nombre_Usuario = Nombre_Jugador.getText();

        pamax = 4;
        
        pa = true;
        
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new BossRush3(Nombre_Usuario,boost_hp,pamax,vida_jugador,fireball,pa));
	marco.setVisible(true);   
        
        
    }//GEN-LAST:event_pa_maxActionPerformed

    private void fire_ballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fire_ballActionPerformed
        // TODO add your handling code here:
        
        
        fireball = true;
      
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new BossRush3(Nombre_Usuario,boost_hp,pamax,vida_jugador,fireball,pa));
	marco.setVisible(true);
    
    }//GEN-LAST:event_fire_ballActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre_Jugador;
    private javax.swing.JButton curacion_jugador;
    private javax.swing.JButton fire_ball;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton pa_max;
    // End of variables declaration//GEN-END:variables
}
