/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BossRush;

import javax.swing.SwingUtilities;
import menucoldware.FrameGeneral;

/**
 *
 * @author sergipaz
 */
public class Eleccion_Jugador extends javax.swing.JPanel {

    /**
     * Creates new form Eleccion_Jugador
     */
    
    int boost_hp;
    int boost_elec;
    int vida_jugador;
    int reduccion_dmg;
    String Nombre_Usuario;
    
    
    public Eleccion_Jugador(String Nombre_Usuario,int vida_jugador) {
        initComponents();
        System.out.println(Nombre_Usuario);
        
        this.vida_jugador = vida_jugador;
        Nombre_Jugador.setText(Nombre_Usuario);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        curacion_jugador = new javax.swing.JButton();
        increment_dmg = new javax.swing.JButton();
        reducir_dmg = new javax.swing.JButton();
        Nombre_Jugador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 768));

        curacion_jugador.setText("+50 de HP ");
        curacion_jugador.setMaximumSize(new java.awt.Dimension(191, 22));
        curacion_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curacion_jugadorActionPerformed(evt);
            }
        });

        increment_dmg.setText("Incrementa tu daño en 10");
        increment_dmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increment_dmgActionPerformed(evt);
            }
        });

        reducir_dmg.setText("Reduce el daño del enemigo en 10");
        reducir_dmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reducir_dmgActionPerformed(evt);
            }
        });

        Nombre_Jugador.setText("Haga su eleccion ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descansi.gif"))); // NOI18N

        jLayeredPane1.setLayer(curacion_jugador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(increment_dmg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(reducir_dmg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Nombre_Jugador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Nombre_Jugador)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(curacion_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(increment_dmg, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(123, 123, 123)
                .addComponent(reducir_dmg)
                .addGap(256, 256, 256))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Nombre_Jugador)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(increment_dmg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reducir_dmg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curacion_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(643, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void curacion_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curacion_jugadorActionPerformed
        // TODO add your handling code here:
        
        String Nombre_Usuario = Nombre_Jugador.getText();
        
        boost_hp = boost_hp +50;
         
        
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new  BossRush2(Nombre_Usuario,boost_hp,boost_elec,vida_jugador,reduccion_dmg));
	marco.setVisible(true);
        
    }//GEN-LAST:event_curacion_jugadorActionPerformed

    private void increment_dmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increment_dmgActionPerformed
        // TODO add your handling code here:
        
        String Nombre_Usuario = Nombre_Jugador.getText();
        
        boost_elec = 10;
        
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new  BossRush2(Nombre_Usuario,boost_hp,boost_elec,vida_jugador,reduccion_dmg));
	marco.setVisible(true);
    }//GEN-LAST:event_increment_dmgActionPerformed

    private void reducir_dmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reducir_dmgActionPerformed
        // TODO add your handling code here:
        
       
        reduccion_dmg = 10;
      
        FrameGeneral marco=(FrameGeneral) SwingUtilities.getWindowAncestor(this);
	marco.remove(this);
	marco.add(new BossRush2(Nombre_Usuario,boost_hp,boost_elec,vida_jugador,reduccion_dmg));
	marco.setVisible(true);
        
        
    
    }//GEN-LAST:event_reducir_dmgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre_Jugador;
    private javax.swing.JButton curacion_jugador;
    private javax.swing.JButton increment_dmg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton reducir_dmg;
    // End of variables declaration//GEN-END:variables
}
